RACK_DIR ?= ../.tmp/Rack-SDK-2.6.6

FLAGS += -I$(CURDIR)/src
SOURCES += $(wildcard src/*.cpp src/dsp/*.cpp)

DISTRIBUTABLES += res
DISTRIBUTABLES += $(wildcard LICENSE*)

include $(RACK_DIR)/plugin.mk
